version: "3.7"
services:
  registry:
    image: registry:2.7.1
    restart: always
    container_name: registry
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/hub.wyq.me.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/hub.wyq.me.key
    ports:
      - "5000:5000"
    volumes:
      - $PWD/registry/data/:/var/lib/registry:rw
      - $PWD/registry/certs:/certs:ro

  nginx:
    depends_on:
      - php
    image: nginx:1.15.8
    restart: always
    container_name: comp_nginx
    ports:
      - "80:80"
    links:
      - php:php
    volumes:
      - $PWD/conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - $PWD/conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/log/nginx/:/var/log/nginx/:rw
      - $PWD/www/:/var/www/:rw
    networks:
      app_net:
         ipv4_address: 10.10.10.3

  php:
    depends_on:
      - mysql
    image: bitnami/php-fpm:7.3.1
    container_name: comp_php
    expose:
      - "9000"
    volumes:
      - $PWD/log/php/:/var/log/php/:rw
      - $PWD/www/:/var/www/:rw
    networks:
      app_net:
        ipv4_address: 10.10.10.2

  mysql:
    image: mysql:5.7
    restart: always
    container_name: comp_mysql
    ports:
      - "3306:3306"
    volumes:
      - $PWD/conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - $PWD/log/mysql/:/var/log/mysql/:rw
      - $PWD/db/:/var/lib/mysql/:rw
      - $PWD/door/:/door/:rw
    environment:
      MYSQL_ROOT_PASSWORD: "rootpasswd"
    networks:
      app_net:
         ipv4_address: 10.10.10.11

networks:
    app_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.10.10.0/24

